import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'si';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    'nav.lms': 'ENTER LMS',
    'nav.joinNow': 'JOIN NOW',
    'hero.badge': 'The Future of Politics Education',
    'hero.title1': 'CB',
    'hero.title2': 'Politics',
    'hero.desc': 'Master the world of Political Science with Chathuranaga Bandara. Absolute clarity, structured concepts, and a path to excellence.',
    'hero.cta.start': 'Start Learning Now',
    'hero.cta.teacher': 'Meet the Teacher',
    'hero.cta.learn': 'Learn More',
    'teacher.badge': 'Teaching Methodology',
    'teacher.title1': 'How We',
    'teacher.title2': 'Revolutionize',
    'teacher.title3': 'Learning',
    'teacher.role': 'Lead Politics Instructor',
    'teacher.exp': 'Years Experience',
    'teacher.success': 'Success Rate',
    'teacher.students': 'Students Taught',
    'programs.title': 'Our',
    'programs.subtitle': 'Programs',
    'programs.desc': 'Engineered for absolute mastery',
    'programs.theory.title': 'Theory Mastery',
    'programs.theory.desc': 'Deep dive into the fundamental concepts of Political Science with conceptual clarity and real-world applications.',
    'programs.revision.badge': 'Fast Track',
    'programs.revision.title': 'Revision Elite',
    'programs.revision.desc': 'Intensive review sessions covering the entire syllabus with focus on high-yield topics.',
    'programs.paper.title': 'Paper Class',
    'programs.exams.title': 'Smart Exams',
    'updates.title': 'Latest Updates',
    'updates.desc': 'Stay informed with CB Politics Terminal',
    'updates.cta': 'Read Full Story',
    'videos.title': 'Class Highlights',
    'videos.desc': 'Experience the energy of our classes',
    'footer.desc': 'Empowering students to reach their highest potential through the power of Political Science. Join the journey to A-grade excellence.',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',
    'footer.contact': 'Contact Us',
    'footer.rights': 'All Rights Reserved.',
    'common.learnMore': 'Learn More',
    'login.student.title': 'Student Portal',
    'login.student.desc': 'Login to access your study materials',
    'login.admin.title': 'Admin Portal',
    'login.admin.desc': 'Authorized access only',
    'login.general.title': 'General Portal',
    'login.general.desc': 'System administration',
    'login.google': 'Login with Google',
    'login.loading': 'Logging in...',
    'login.error.unregistered': 'Student email not registered. Please contact Admin.',
    'login.error.unpaid': "You haven't paid for this month. Please contact Admin.",
    'dash.welcome': 'Welcome back',
    'dash.logout': 'Logout',
    'dash.student.materials': 'Study Materials',
    'dash.student.noMaterials': 'No materials available for your grade yet.',
    'dash.admin.overview': 'Overview',
    'dash.admin.students': 'Students',
    'dash.admin.videos': 'Videos',
    'dash.admin.home': 'Home Content',
    'dash.student.paymentRequired': 'Payment Required',
    'dash.student.paymentDesc': "You haven't paid for this month. Please contact the Admin to activate your account.",
    'dash.student.backToLessons': 'Back to Lessons',
    'dash.student.lessonUploaded': 'Lesson uploaded on',
    'dash.student.joinNow': 'Join Now',
    'dash.student.noLive': 'No active live classes at the moment.',
    'dash.tabs.studyPacks': 'Study Packs',
    'dash.tabs.live': 'Live Classes',
    'dash.tabs.recordings': 'Recordings',
    'dash.tabs.marks': 'Marks',
    'dash.tabs.batches': 'Batches',
    'dash.student.noRecordings': 'No encrypted recordings found for this partition.',
    'dash.student.backToRecordings': 'Back to Recordings',
    'dash.student.performanceIndex': 'Performance Index',
    'dash.student.examPaper': 'Examination Paper',
    'dash.student.aggregateMarks': 'Aggregate Marks',
    'dash.student.batchStanding': 'Batch Standing',
    'dash.student.dateRecorded': 'Date Recorded',
    'dash.student.noRecords': 'No academic records found in terminal.',
    'dash.student.welcomeTitle': 'Welcome,',
    'dash.student.welcomeDesc': 'Your entry record is now active. This is your unique Identification Serial. Keep it secure for all academic validations.',
    'dash.student.identificationSerial': 'Official Identification Serial',
    'dash.student.commitToMemory': 'COMMIT TO MEMORY',
    'dash.student.terminalAutoSecured': 'Terminal identification auto-secures after first view.',
    'dash.admin.totalStudents': 'Total Students',
    'dash.admin.studyPacks': 'Study Packs',
    'dash.admin.liveClasses': 'Live Classes',
    'dash.admin.addNewLesson': 'Add New Lesson',
    'dash.admin.uploadLesson': 'Upload Lesson',
    'dash.admin.registerStudent': 'Register New Student',
    'dash.admin.addStudent': 'Add Student',
    'dash.admin.scheduleLive': 'Schedule Live Class',
    'dash.admin.startLive': 'Start Live Class',
    'dash.admin.teacherInfo': 'Teacher Information',
    'dash.admin.saveChanges': 'Save Changes',
    'dash.admin.addPost': 'Add Home Post',
    'dash.admin.addVideo': 'Add Home Video',
    'dash.admin.myClasses': 'My Classes',
    'dash.admin.manageAdmins': 'Manage Admins',
    'dash.admin.backToHome': 'Back to Home',
    'dash.admin.activePosts': 'Active Posts',
    'dash.admin.activeVideos': 'Active Videos',
    'dash.tabs.home': 'Home',
    'dash.tabs.dashboard': 'Dashboard',
    'dash.admin.name': 'Name',
    'dash.admin.email': 'Email',
    'dash.admin.class': 'Class',
    'dash.admin.payment': 'Payment',
    'dash.admin.actions': 'Actions',
    'dash.admin.paymentHistory': 'Payment History',
    'dash.admin.historyFor': 'History for',
    'dash.admin.paid': 'PAID',
    'dash.admin.unpaid': 'UNPAID',
    'dash.admin.noHistory': 'No payment history found.',
    'dash.admin.close': 'Close',
    'login.title.success': 'Registration Done',
    'login.title.signin': 'Sign In',
    'login.title.register': 'Register',
    'login.subtitle.success': 'Welcome to the portal',
    'login.subtitle.signin': 'Access your learning portal',
    'login.subtitle.register': 'Join the premium CB Politics experience',
    'login.google.or': 'or use google',
    'login.button.gotoLogin': 'GOTO LOGIN',
    'login.button.google': 'SIGN IN WITH GOOGLE',
    'login.button.signin': 'GET STARTED',
    'login.button.register': 'COMPLETE JOIN',
    'login.link.noAccount': 'No account?',
    'login.link.hasAccount': 'Has account?',
    'login.label.whatsapp': 'WhatsApp',
    'login.label.index': 'Index No',
    'login.label.name': 'Full Name',
    'login.label.year': 'Exam Year',
    'login.label.nic': 'NIC/ID',
    'login.label.class': 'Class',
    'login.label.school': 'School',
    'login.label.address': 'Address',
    'login.label.password': 'Admin Password',
    'login.label.masterPassword': 'Master Password',
    'home.transmissionSource': 'TRANSMISSION_SOURCE',
    'home.accessPortal': 'Access_Portal',
    'home.viewResults': 'View All Results',
    'home.syncProtocol': 'SYNC_PROTOCOL',
    'home.meetEducator': 'Meet The Educator',
    'home.initComms': 'INIT_COMMS',
    'home.baseTerminal': 'Our Base Terminal',
    'home.hotline': 'Transmission Hotline',
    'home.terminalName': 'CB Politics Learning Terminal',
    'home.teacherBioDefault': 'Achieving 4th place in the island in the 2017 A/L Biology stream, he is currently completing his degree at the Colombo Faculty of Medicine. Entering the tuition field in 2019, within less than 4 years, he created the Bio class with the highest student participation in the island.'
  },
  si: {
    'nav.lms': 'LMS වෙත පිවිසෙන්න',
    'nav.joinNow': 'දැන්ම සම්බන්ධ වන්න',
    'hero.badge': 'ජීව විද්‍යා අධ්‍යාපනයේ අනාගතය',
    'hero.title1': 'Bio',
    'hero.title2': 'Science',
    'hero.desc': 'භාෂන විතානගේ සමඟ Bio ලෝකය ප්‍රගුණ කරන්න. පැහැදිලි ඉගැන්වීම්, විෂය නිර්දේශයට අනුකූල මගපෙන්වීම් සහ විශිෂ්ටත්වය කරා යන මාවතක්.',
    'hero.cta.start': 'දැන්ම ඉගෙනීම අරඹන්න',
    'hero.cta.teacher': 'ගුරුවරයා හමුවන්න',
    'hero.cta.learn': 'වැඩිදුර ඉගෙනීමට',
    'teacher.badge': 'ඉගැන්වීමේ ක්‍රමවේදය',
    'teacher.title1': 'අපි කොහොමද',
    'teacher.title2': 'විප්ලවීය',
    'teacher.title3': 'ඉගෙනීම',
    'teacher.role': 'ප්‍රධාන Bio උපදේශක',
    'teacher.exp': 'වසරක පළපුරුද්ද',
    'teacher.success': 'සාර්ථකත්ව අනුපාතය',
    'teacher.students': 'සිසුන් සංඛ්‍යාව',
    'programs.title': 'අපගේ',
    'programs.subtitle': 'වැඩසටහන්',
    'programs.desc': 'පරිපූර්ණ ප්‍රවීණතාවය සඳහා නිර්මාණය කර ඇත',
    'programs.theory.title': 'සිද්ධාන්ත ප්‍රවීණතාවය',
    'programs.theory.desc': 'සංකල්පීය පැහැදිලිකම සහ විෂය නිර්දේශයට අනුකූලව Bio මූලික නියමයන් ගැඹුරින් අධ්‍යයනය කරන්න.',
    'programs.revision.badge': 'වේගවත් මාවත',
    'programs.revision.title': 'පුනරීක්ෂණ එලයිට්',
    'programs.revision.desc': 'වැදගත් මාතෘකා කෙරෙහි අවධානය යොමු කරමින් සමස්ත විෂය නිර්දේශය ආවරණය වන දැඩි සමාලෝචන සැසි.',
    'programs.paper.title': 'ප්‍රශ්න පත්‍ර පන්තිය',
    'programs.exams.title': 'ස්මාර්ට් විභාග',
    'updates.title': 'නවතම යාවත්කාලීන',
    'updates.desc': 'Bio Terminal සමඟ යාවත්කාලීනව සිටින්න',
    'updates.cta': 'සම්පූර්ණ විස්තරය කියවන්න',
    'videos.title': 'පන්තිවල විශේෂ අවස්ථා',
    'videos.desc': 'අපගේ පන්තිවල ශක්තිය අත්විඳින්න',
    'footer.desc': 'Bio තුළින් සිසුන්ට ඔවුන්ගේ ඉහළම විභවය කරා ළඟා වීමට බලය ලබා දීම. අදම අප සමඟ එක්වන්න.',
    'footer.privacy': 'පෞද්ගලිකත්ව ප්‍රතිපත්තිය (Privacy Policy)',
    'footer.terms': 'සේවා කොන්දේසි (Terms of Service)',
    'footer.contact': 'Contact Us',
    'footer.rights': 'All Rights Reserved.',
    'common.learnMore': 'වැඩි විස්තර',
    'login.student.title': 'ශිෂ්‍ය ද්වාරය',
    'login.student.desc': 'ඔබේ අධ්‍යයන ද්‍රව්‍ය ලබා ගැනීමට ලොග් වන්න',
    'login.admin.title': 'පරිපාලක ද්වාරය',
    'login.admin.desc': 'බලයලත් ප්‍රවේශය පමණි',
    'login.general.title': 'පොදු ද්වාරය',
    'login.general.desc': 'පද්ධති පරිපාලනය',
    'login.google': 'Google සමඟ ලොග් වන්න',
    'login.loading': 'ලොග් වෙමින් පවතී...',
    'login.error.unregistered': 'ශිෂ්‍ය විද්‍යුත් තැපෑල ලියාපදිංචි කර නැත. කරුණාකර පරිපාලක අමතන්න.',
    'login.error.unpaid': 'ඔබ මෙම මාසය සඳහා ගෙවා නැත. කරුණාකර පරිපාලක අමතන්න.',
    'dash.welcome': 'නැවත සාදරයෙන් පිළිගනිමු',
    'dash.logout': 'ලොග් අවුට් වන්න',
    'dash.student.materials': 'අධ්‍යයන ද්‍රව්‍ය',
    'dash.student.noMaterials': 'ඔබේ ශ්‍රේණිය සඳහා තවමත් ද්‍රව්‍ය නොමැත.',
    'dash.admin.overview': 'දළ විශ්ලේෂණය',
    'dash.admin.students': 'සිසුන්',
    'dash.admin.videos': 'වීඩියෝ',
    'dash.admin.home': 'මුල් පිටුවේ අන්තර්ගතය',
    'dash.student.paymentRequired': 'ගෙවීම් අවශ්‍යයි',
    'dash.student.paymentDesc': 'ඔබ මෙම මාසය සඳහා ගෙවා නැත. කරුණාකර ඔබේ ගිණුම සක්‍රිය කිරීමට පරිපාලක අමතන්න.',
    'dash.student.backToLessons': 'නැවත පාඩම් වෙත',
    'dash.student.lessonUploaded': 'පාඩම උඩුගත කළ දිනය',
    'dash.student.joinNow': 'දැන්ම සම්බන්ධ වන්න',
    'dash.student.noLive': 'මේ මොහොතේ සක්‍රීය සජීවී පන්ති නොමැත.',
    'dash.tabs.studyPacks': 'අධ්‍යයන පැකේජ (Study Packs)',
    'dash.tabs.live': 'සජීවී පන්ති (Live Classes)',
    'dash.tabs.recordings': 'පටිගත කළ පන්ති (Recordings)',
    'dash.tabs.marks': 'ප්‍රතිඵල (Marks)',
    'dash.tabs.batches': 'කණ්ඩායම් (Batches)',
    'dash.student.noRecordings': 'මෙම කොටස සඳහා කිසිදු පටිගත කිරීමක් හමු නොවීය.',
    'dash.student.backToRecordings': 'නැවත පටිගත කළ පන්ති වෙත',
    'dash.student.performanceIndex': 'දක්ෂතා දර්ශකය',
    'dash.student.examPaper': 'විභාග ප්‍රශ්න පත්‍රය',
    'dash.student.aggregateMarks': 'මුළු ලකුණු',
    'dash.student.batchStanding': 'කණ්ඩායමේ ස්ථානය',
    'dash.student.dateRecorded': 'වාර්තාගත දිනය',
    'dash.student.noRecords': 'පද්ධතිය තුළ අධ්‍යයන වාර්තා හමු නොවීය.',
    'dash.student.welcomeTitle': 'සාදරයෙන් පිළිගනිමු,',
    'dash.student.welcomeDesc': 'ඔබේ ඇතුළත් කිරීම් වාර්තාව දැන් සක්‍රීයයි. මෙය ඔබගේ අනන්‍ය හඳුනාගැනීමේ අංකයයි. සියලුම අධ්‍යයන කටයුතු සඳහා එය සුරක්ෂිතව තබා ගන්න.',
    'dash.student.identificationSerial': 'නිල හඳුනාගැනීමේ අංකය',
    'dash.student.commitToMemory': 'මතක තබා ගන්න',
    'dash.student.terminalAutoSecured': 'පළමු නැරඹීමෙන් පසු හඳුනාගැනීමේ අංකය ස්වයංක්‍රීයව සුරක්ෂිත වේ.',
    'dash.admin.totalStudents': 'මුළු සිසුන් සංඛ්‍යාව',
    'dash.admin.studyPacks': 'අධ්‍යයන පැකේජ',
    'dash.admin.liveClasses': 'සජීවී පන්ති',
    'dash.admin.addNewLesson': 'නව පාඩමක් එක් කරන්න',
    'dash.admin.uploadLesson': 'පාඩම උඩුගත කරන්න',
    'dash.admin.registerStudent': 'නව ශිෂ්‍යයෙකු ලියාපදිංචි කරන්න',
    'dash.admin.addStudent': 'ශිෂ්‍යයා එක් කරන්න',
    'dash.admin.scheduleLive': 'සජීවී පන්තියක් සැලසුම් කරන්න',
    'dash.admin.startLive': 'සජීවී පන්තිය අරඹන්න',
    'dash.admin.teacherInfo': 'ගුරුවරයාගේ තොරතුරු',
    'dash.admin.saveChanges': 'වෙනස්කම් සුරකින්න',
    'dash.admin.addPost': 'මුල් පිටුවට පෝස්ට් එකක් එක් කරන්න',
    'dash.admin.addVideo': 'මුල් පිටුවට වීඩියෝවක් එක් කරන්න',
    'dash.admin.myClasses': 'මගේ පන්ති',
    'dash.admin.manageAdmins': 'පරිපාලකයින් කළමනාකරණය',
    'dash.admin.backToHome': 'මුල් පිටුවට',
    'dash.admin.activePosts': 'සක්‍රීය පෝස්ට්',
    'dash.admin.activeVideos': 'සක්‍රීය වීඩියෝ',
    'dash.tabs.home': 'මුල් පිටුව',
    'dash.tabs.dashboard': 'ඩෑෂ්බෝඩ්',
    'dash.admin.name': 'නම',
    'dash.admin.email': 'විද්‍යුත් තැපෑල',
    'dash.admin.class': 'පන්තිය',
    'dash.admin.payment': 'ගෙවීම්',
    'dash.admin.actions': 'ක්‍රියාමාර්ග',
    'dash.admin.paymentHistory': 'ගෙවීම් ඉතිහාසය',
    'dash.admin.historyFor': 'ඉතිහාසය - ',
    'dash.admin.paid': 'ගෙවා ඇත',
    'dash.admin.unpaid': 'ගෙවා නැත',
    'dash.admin.noHistory': 'ගෙවීම් ඉතිහාසයක් හමු නොවීය.',
    'dash.admin.close': 'වසා දමන්න',
    'login.title.success': 'ලියාපදිංචිය සාර්ථකයි',
    'login.title.signin': 'Sign In',
    'login.title.register': 'ලියාපදිංචි වන්න',
    'login.subtitle.success': 'ද්වාරය වෙත සාදරයෙන් පිළිගනිමු',
    'login.subtitle.signin': 'ඔබේ ඉගැන්වීම් ද්වාරය වෙත පිවිසෙන්න',
    'login.subtitle.register': 'ප්‍රමුඛ Bio අත්දැකීම සමඟ එක්වන්න',
    'login.google.or': 'නැතහොත් Google භාවිතා කරන්න',
    'login.button.gotoLogin': 'LOGIN වෙත යන්න',
    'login.button.google': 'SIGN IN WITH GOOGLE',
    'login.button.signin': 'ආරම්භ කරන්න',
    'login.button.register': 'සම්බන්ධ වීම අවසන් කරන්න',
    'login.link.noAccount': 'ගිණුමක් නොමැතිද?',
    'login.link.hasAccount': 'ගිණුමක් තිබේද?',
    'login.label.whatsapp': 'WhatsApp',
    'login.label.index': 'දර්ශක අංකය',
    'login.label.name': 'සම්පූර්ණ නම',
    'login.label.year': 'විභාග වර්ෂය',
    'login.label.nic': 'ජාතික හැඳුනුම්පත් අංකය',
    'login.label.class': 'පන්තිය',
    'login.label.school': 'පාසල',
    'login.label.address': 'ලිපිනය',
    'login.label.password': 'පරිපාලක මුරපදය',
    'login.label.masterPassword': 'ප්‍රධාන මුරපදය',
    'home.transmissionSource': 'TRANSMISSION_SOURCE',
    'home.accessPortal': 'Access_Portal',
    'home.viewResults': 'View All Results',
    'home.syncProtocol': 'SYNC_PROTOCOL',
    'home.meetEducator': 'Meet The Educator',
    'home.initComms': 'INIT_COMMS',
    'home.baseTerminal': 'Our Base Terminal',
    'home.hotline': 'Transmission Hotline',
    'home.terminalName': 'Politics Learning Terminal',
    'home.teacherBioDefault': '2017 උසස් පෙළ ජීව විද්‍යා අංශයෙන් දිවයිනේ 4 වන ස්ථානයට සමත්ව මේ වන විට කොළඹ වෛද්‍ය පීඨයේ සිය උපාධිය අවසන් කරමින් සිටියිය. 2019 දී උපකාරක පන්ති ක්ෂේත්‍රයට පිවිසෙන ඔහු වසර 4ක් යන්නටත් පෙර දිවයිනේ වැඩිම සිසුන් පිරිසක් සහභාගි වන Bio පන්තිය නිර්මාණය කරයි.'

  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('app-language');
    return (saved as Language) || 'en';
  });

  useEffect(() => {
    localStorage.setItem('app-language', language);
  }, [language]);

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
